version: '2'
services:
  kong:
    image: mashape/kong
    security_opt:
      - seccomp:unconfined
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database:kong-database
    depends_on:
      - kong-database
  kong-database:
    image: cassandra:2.2
